#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N ph_significance
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# group significance
group_significance.py \
-i ~/outputs/open_reference_otus/otu_table_mc2.biom \
-m ~/2018_02_smb/map.tsv \
-c SamplePh \
-s ANOVA \
-o ~/outputs/group_significance/

# deactivate virtualenv
source deactivate
