#!/bin/bash -login
#PBS -l walltime=10:00:00
#PBS -l select=1:ncpus=4
#PBS -N closed_reference_otu
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# pick closed reference OTUs
time pick_closed_reference_otus.py \
-i ~/2018_02_smb/seqs.fna \
-o ~/outputs/closed_reference_otus \
-a \
-O 2

# deactivate virtualenv
source deactivate
