#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N core_microbiome
#PBS -A d411-training

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# compute core microbiome
compute_core_microbiome.py \
-i ~/2018_02_smb/de_novo_otus/otu_table.biom \
-o ~/outputs/core_microbiome

# deactivate virtualenv
source deactivate
