#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N comparing categories
#PBS -A d411-training

# load module
module load miniconda/python2

# activate virtualenv
source activate qiime1

# create temporary directory
export TMPDIR=~/qiime_tmp

# compare categories
compare_categories.py \
--method adonis \
-i ~/2018_02_smb/core_diversity_analyses/bdiv_even600/unweighted_unifrac_dm.txt \
-m ~/2018_02_smb/map_incomplete.tsv \
-c HOST_SUBJECT_ID \
-o ~/2018_02_smb/adonis_out \
-n 999

# deactivate vitrualenv
source deactivate
