#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=48
#PBS -N core_diversity_analyses
#PBS -A d411-training

# load module
module load miniconda/python2


# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# core diversity analyses
time core_diversity_analyses.py \
-i ~/2018_02_smb/de_novo_otus/otu_table.biom \
-m ~/2018_02_smb/map_incomplete.tsv \
-t ~/2018_02_smb/de_novo_otus/rep_set.tre \
-o ~/outputs/core_diversity_analyses \
-e 600 \
-a \
-O 24

# deactivate virtualenv
source deactivate
