#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N split_libraries
#PBS -A d411-training

# load module
module load miniconda/python2

# activate virtualenv
source activate qiime1

# establish temporary directory
export TMPDIR=~/qiime_tmp

# split libraries

time split_libraries_fastq.py \
-m ~/2018_02_smb/map_incomplete.tsv \
-i ~/2018_02_smb/Read1.fastq.gz \
-b ~/2018_02_smb/Index.fastq.gz \
-o ~/2018_02_smb \
-q 19 \
--barcode_type 12
