
#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=16
#PBS -N align_seqs
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# align seqs
time parallel_align_seqs_pynast.py \
-i ~/outputs/rep_set.fna \
-t ~/SILVA_132_QIIME_release/rep_set_aligned/97/97_alignment.fna \
-o ~/outputs/aligned_seqs \
-a \
-O 8

# deactivate virtualenv
source deactivate
