#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N comparing_SampleDepth
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# compare categories
compare_categories.py \
--method anosim \
-i ~/outputs/core_diversity_analyses/bdiv_even600/unweighted_unifrac_dm.txt \
-m ~/2018_02_smb/map.tsv \
-c SampleDepth \
-o ~/outputs/anosim_out \
-n 748

# deactivate vitrualenv
source deactivate
