#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=48
#PBS -N core_diversity_analyses
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# core diversity analyses
time core_diversity_analyses.py \
-i ~/outputs/open_reference_otus/otu_table_mc2.biom \
-m ~/2018_02_smb/map.tsv \
-t ~/outputs/open_reference_otus/rep_set.tre \
-o ~/outputs/core_diversity_analyses \
-e 600 \
-a \
-O 24

# deactivate virtualenv
source deactivate
