
#!/bin/bash -login
#PBS -l walltime=1:00:00
#PBS -l select=1:ncpus=48
#PBS -N de_novo_otu_taxonomy
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# split de novo OTU table by taxonomy
time split_otu_table_by_taxonomy.py \
-i ~/2018_02_smb/de_novo_otus/otu_table.biom \
-o ~/outputs/
-L 2

# deactivate virtualenv
source deactivate
