#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N filter_alignment
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# filter aligned seqs
time filter_alignment.py \
-i ~/outputs/aligned_seqs/rep_set_aligned.fasta \
-o ~/outputs/filtered_aligned_seqs 

# deactivate virtualenv
source deactivate
