#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=24
#PBS -N identify_chimeras
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# identify chimeras
time identify_chimeric_seqs.py \
-i ~/outputs/aligned_seqs/rep_set_aligned.fasta \
-m ChimeraSlayer \
-a ~/SILVA_132_QIIME_release/rep_set_aligned/97/97_alignment.fna \
-o ~/outputs/chimeric_seqs.txt \
-O 12

# deactivate virtualenv
source deactivate
