#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=48
#PBS -N 2018_join_paired_ends
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load modules
module load eb
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo “loading virtualenv”
source activate qiime1

# joining paired ends
time join_paired_ends.py \
-m SeqPrep \
-b ~/2018_02_smb/Index.fastq.gz \
-f ~/2018_02_smb/Read1.fastq.gz \
-r ~/2018_02_smb/Read2.fastq.gz \
-o ~/outputs/SeqPrep_joined

# deactivating virtualenv
source deactivate 
