
#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N phylogeny
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

make_phylogeny.py \
-i ~/outputs/filtered_aligned_seqs/rep_set_aligned_pfiltered.fasta \
-o ~/outputs/phylogeny_tree.tre

# deactivate virtualenv
source deactivate
