#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N otu_heatmap
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# make otu heatmap
time make_otu_heatmap.py \
-i ~/outputs/de_novo_core_microbiome/core_table_95.biom \
-m ~/2018_02_smb/update_map.tsv \
-t ~/outputs/de_novo_otus/rep_set.tre \
-o ~/outputs/otu_heatmap

# deactivate virtualenv
source deactivate
