
#!/bin/bash -login
#PBS -l walltime=1:00:00
#PBS -l select=1:ncpus=48
#PBS -N phylum_taxonomy
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# split silva OTU table by taxonomy
time split_otu_table_by_taxonomy.py \
-i ~/outputs/silva_otus/otu_table.biom \
-o ~/outputs/phylum_taxonomy
-L 2

# deactivate virtualenv
source deactivate
