#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N pick_rep_set
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# pick rep set
time pick_rep_set.py \
-i ~/outputs/silva_otus/uclust_ref_picked_otus/seqs_otus.txt \
-f ~/outputs/split_libraries/seqs.fna \
-r ~/SILVA_132_QIIME_release/rep_set/rep_set_16S_only/97/silva_132_97_16S.fna \
-o ~/outputs/rep_set.fna

# deactivate virtualenv
source deactivate
