#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N split_libraries
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# establish temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# split libraries
time split_libraries_fastq.py \
-m ~/2018_02_smb/map.tsv \
-i ~/2018_02_smb/Read1.fastq.gz \
-b ~/2018_02_smb/Index.fastq.gz \
-o ~/outputs/split_libraries \
-q 19 \
--barcode_type 12

# deactivate virtualenv
source deactivate
