#!/bin/bash -login
#PBS -l walltime=10:00:00
#PBS -l select=1:ncpus=4
#PBS -N open_reference_otu
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# pick open reference OTUs
time pick_open_reference_otus.py \
-i ~/outputs_17/seqs.fna \
-o ~/outputs_17/open_reference_otus \
-a \
-O 2

# deactivate virtualenv
source deactivate
