#!/bin/bash -login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=16
#PBS -N silva_closed_otus
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# pick closed reference OTUs with SILVA
time pick_closed_reference_otus.py \
-r ~/SILVA_132_QIIME_release/rep_set/rep_set_16S_only/97/silva_132_97_16S.fna \
-i ~/outputs_17/split_libraries/seqs.fna \
-o ~/outputs_17/silva_otus \
-t ~/SILVA_132_QIIME_release/taxonomy/16S_only/97/majority_taxonomy_7_levels.txt \
-a \
-O 8

# deactivate virtualenv
source deactivate
