#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=48
#PBS -N corediv_3000
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# core diversity analyses
time core_diversity_analyses.py \
-i ~/outputs/update_map/silva_otus/otu_table.biom \
-m ~/2018_02_smb/update_map.tsv \
-t ~/SILVA_132_QIIME_release/trees/97/97_otus.tre \
-o ~/outputs/update_map/corediv_3000 \
-e 3000 \
-a \
-O 24

# deactivate virtualenv
source deactivate
