#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N comparing_depth
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# compare categories
compare_categories.py \
--method anosim \
-i ~/outputs/de_novo_corediv3000/bdiv_even3000/unweighted_unifrac_dm.txt \
-m ~/2018_02_smb/update_map.tsv \
-c SampleDepth \
-o ~/outputs/anosim/depth \
-n 3000

# deactivate vitrualenv
source deactivate
