#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N core_microbiome
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# compute core microbiome
compute_core_microbiome.py \
-i ~/outputs_16/silva_otus/otu_table.biom \
-o ~/outputs_16/core_microbiome

# deactivate virtualenv
source deactivate
