#!/bin/bash -login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N open_reference_otu
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# pick open reference OTUs
time pick_open_reference_otus.py \
-i ~/outputs_16/split_libraries/seqs.fna \
-o ~/outputs_16/open_reference_otus \
-a \
-O 16

# deactivate virtualenv
source deactivate
