#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N otu_heatmap
#PBS -A d411-training

cd $PBS_O_WORKDIR

# load module
module load miniconda/python2

# create temporary directory
export TMPDIR=~/qiime_tmp

# activate virtualenv
source activate qiime1

# make otu heatmap
time make_otu_heatmap.py \
-i ~/outputs/core_microbiome/core_table_95.biom \
-m ~/2018_02_smb/map.tsv \
-t ~/SILVA_132_QIIME_release/taxonomy/16S_only/97/majority_taxonomy_7_levels.txt \
-o ~/outputs/otu_heatmap

# deactivate virtualenv
source deactivate
